### ISSUE TITLE
[CY-2693] Wrong redirect in https://github.com/codacy/codacy-analysis-cli/releases/latest

### ISSUE THREAD

**Issue by gasrios** [codacy/codacy-analysis-cli#285]
This not not a code issue.

https://github.com/codacy/codacy-analysis-cli/releases/latest is currently redirecting to https://github.com/codacy/codacy-analysis-cli/releases/tag/2.1.0 , not https://github.com/codacy/codacy-analysis-cli/releases/tag/3.3.4 , the latest release at the time the problem was noticed.

This is preventing scripts that rely on this information to correctly update codacy-analysis-cli to the latest version (see https://github.com/gasrios/localops/blob/ubuntu_focal_fossa/codacy-analysis-cli.yaml )

**Comment by josemiguelmelo** [comment]
Hi @gasrios ,

Thanks for warning us about the redirect on the latest release. It should be fixed now.

About the CLI being updated to the latest version, we currently are using the stable version by default when installing the CLI. This means that when you do `make install` it will download and install the most recent stable version and the CLI will be automatically updated, so it should be using the latest stable. If you want to use a specific version instead of the stable one, you need to specify the version by passing an environment variable (https://github.com/codacy/codacy-analysis-cli#environment-variables).

Thanks,

**Comment by gasrios** [comment]
Thanks @josemiguelmelo , I just retested it and can confirm the issue was fixed. Closing issue.

BTW, automated scripts such as the one I use will rely in the version number informed by the redirect, so, even if the correct version is installed, it will register as a previous one, so I really appreciate this was fixed. =^)
