### ISSUE TITLE
[CY-2997] directory' with relatively path cause an error

### ISSUE THREAD

**Issue by TheColdPot** [codacy/codacy-analysis-cli#314]
But when I try to add a `directory`, it says
```
docker: Error response from daemon: invalid volume specification: 'src/peb.js:src/peb.js': invalid mount config for type "volume": invalid mount path: 'src/peb.js' mount path must be absolute.
```
It seems to need an absolute path, but how to write this absolute path

**Comment by franciscodua** [comment]
Hi @TheColdPot 

You can either write the absolute path to your folder or `$PWD/src`.
You can use the $PWD if:
1. You're using a UNIX based system, e.g., linux or MacOS
2. You're running the command from the folder where you have the src folder

This is happening because the CLI is trying to launch a Docker container and mapping your directory to the containers. However, this requires an absolute path on the host machine (yours), as you can check [here](https://docs.docker.com/storage/bind-mounts/) or follow this GitHub thread [here](https://github.com/moby/moby/issues/4830).

Let us know if this solution works for you. Meanwhile, I'll update our documentation with this information that the directory should be an absolute path

**Comment by franciscodua** [comment]
I just noticed you're using the GitHub action in an open-source project 😅. This way is easier to understand what's going on.

In [here](https://github.com/TechPot-Studio/peb.js/blob/master/.github/workflows/push-check.yml#L41) it looks you're trying to pass a list of javascript files to be analyzed. But the `directory` parameter should be a directory only. So, you should pass the `src` only.

However, if your goal is to analyze javascript files only, you can run it for the whole repository (without specifying that parameter) and add a configuration file to your root folder like [this](https://docs.codacy.com/repositories-configure/codacy-configuration-file/). In this configuration file, you can specify which tools should run, and even if you want to exclude some files.

I hope this helps more than the previous answer.

**Comment by TheColdPot** [comment]
OK, but then it says
```

Digest: sha256:d482d5f80852881de4012ea113db4cc526944501ae1bd2a87c323e2359f211d8
Status: Downloaded newer image for codacy/codacy-analysis-cli:stable
docker: Error response from daemon: invalid volume specification: 'src:src': invalid mount config for type "volume": invalid mount path: 'src' mount path must be absolute.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

**Comment by TheColdPot** [comment]
In this case, can I put .jshintrc in **the `src/` directory**?

**Comment by TheColdPot** [comment]
https://github.com/TechPot-Studio/peb.js/runs/1218430430
Okay, so now this is resolved
But what if I want to put .jshintrc in the root directory?

**Comment by franciscodua** [comment]
>Okay, so now this is resolved

Glad to hear it

>But what if I want to put .jshintrc in the root directory?

I would say to evaluate your root directory (leave the directory value as default), instead of targeting the `src` directory. The tool is meant to target a repository's root and ignore files if you want to. And to ignore these files you can use the `.codacy.yml` configuration file (https://docs.codacy.com/repositories-configure/codacy-configuration-file/).

An example of `.codacy.yml` for your project could be
```yaml
---
exclude_paths:
  - .github/**
  - docs/**
  - dist/**

```

**Comment by TheColdPot** [comment]
> This way you can have the .jshintrc in the root directory

Very thanks! If you think this problem can be completely resolved, you can Close Issue, but if you want to keep it for a few days to avoid the same problem, keep it

**Comment by franciscodua** [comment]
Thanks for bearing with us.
I'll close this and point similar problems to this thread
