### ISSUE TITLE
[CY-3125] codacy-analysis-cli in GitHub Codacy Security Scan Action fails

### ISSUE THREAD

**Issue by Jmcleodfoss** [codacy/codacy-analysis-cli#330]
I have three Java projects, and the Codacy Security Scan works for two of them, but fails for the third. I have attached the log files for the project which fails. I seen a java.lang.IndexOutOfBoundsException thrown in the project where this fails, but I lack the expertise to track down the reason.

All three projects have been published on GitHub, so the logs can be viewed directly in situ. The one which fails is:

- https://github.com/Jmcleodfoss/pstreader

the two which succeed are:

- https://github.com/Jmcleodfoss/msgreader
- https://github.com/Jmcleodfoss/VoluminousPaginationSkin

I have excluded processing of some file types which appear only in the failing project, but it has made no difference; I cannot figure out what else to try.

[logs_59.zip](https://github.com/codacy/codacy-analysis-cli/files/5424116/logs_59.zip)

**Comment by machadoit** [comment]
Hi @Jmcleodfoss do you have the repository added on [Codacy](https://www.codacy.com) ? And your `CODACY_PROJECT_TOKEN` set? If so, please contact us from Codacy support, and do mention this ticket.

In case you are using this action without Codacy, keep in mind that multiple tools are failing on your repositories, because those tools need configurations. The action only fails if all the tools fail, on all of your examples you have partial failures of specific tools.

If this is the case, I suggest that you do **either**: 

Add the configuration for the underlying tool you want to run; OR Add the repository on Codacy, and setting the value of `CODACY_PROJECT_TOKEN` on your repository secrets (/settings/secrets).

**Comment by Jmcleodfoss** [comment]
Hi @machadoit, that is understood, and I am setting that up now, but I was electing to take advantage of the comment:

`# You can also omit the token and run the tools that support default configurations` in the [project's codacy-analysis workflow description](https://github.com/Jmcleodfoss/pstreader/blob/master/.github/workflows/codacy-analysis.yml). This approach worked fine for the other two projects (as mentioned), but fails with this one.

**Comment by Jmcleodfoss** [comment]
This is working now. I conjecture that I ran into some limitation with the sheer number of problems Codacy found with default settings and once I cleared a few hundred of them, it started working properly.
